name: skot
description: "Streaming Service for SKOT Label"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.0
  just_audio_mpv: ^0.1.7
  audio_video_progress_bar: ^2.0.1
  salomon_bottom_bar: ^3.3.2
  palette_generator: ^0.3.3+3
  http: ^0.13.3
  just_audio_background: ^0.0.1-beta.11
  shared_preferences: ^2.2.2
  just_audio_web: ^0.4.9
  audio_service: ^0.18.12
  background_fetch: ^1.2.2
  awesome_notifications: ^0.9.2
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/default_cover.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/skot.png"
  min_sdk_version: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/skot_white.png"
    background_color: "#000000"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/skot.png"
    icon_size: 128
  macos:
    generate: true
    image_path: "assets/images/skot.png"
