buildscript {
    ext.kotlin_version = '2.1.0' // Version compatible de Kotlin
    ext {
        compileSdkVersion = 36
        minSdkVersion = 35
        targetSdkVersion = 36
        appCompatVersion = "1.4.2"
        ndkVersion = "28.0.12433566"
        buildToolsVersion = "36.0.0"
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.android.tools.build:gradle:8.12.0' // Version compatible avec Gradle 8.13
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
